# docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playlister-production
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=production
      - PORT=8888
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - gibbs-apps
    volumes:
      - ./logs:/usr/src/app/logs:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      - "app=playlister"
      - "environment=production"

networks:
  gibbs-apps:
    external: true